### PR TITLE
[WEB-5548]: Updated Profile.updateProfile

### PR DESCRIPTION
**Pull request by aosmakserato**
Replace param country with param country_code in `Profile.updateProfile` method.

### CODE REVIEW

**Review by GuillaumeBrousse — APPROVED** [review]
LGTM

**Review by mshahidi — APPROVED** [review]
Looks good.
As it is a breaking change, we should bump up the major version.

**Comment by GuillaumeBrousse** [comment]
@mshahidi don't really need to, it's not used under `console-app` and on `profile-app` it's hardly use as it's optional so it's not a real break changes

**Comment by mshahidi** [comment]
> @mshahidi don't really need to, it's not used under `console-app` and on `profile-app` it's hardly use as it's optional so it's not a real break changes

This is a breaking change from API point of view, regardless it is used or not. So we always should follow the rule when creating releases in the API. 
This case is an exception from client side point of view because the `country` was not used. We still need to update `Profile.d.ts` file in `console-app` after updating the SDK version.

**Comment by mshahidi** [comment]
> > @mshahidi don't really need to, it's not used under `console-app` and on `profile-app` it's hardly use as it's optional so it's not a real break changes
> 
> This is a breaking change from API point of view, regardless it is used or not. So we always should follow the rule when creating releases in the API.
> This case is an exception from client side point of view because the `country` was not used. We still need to update `Profile.d.ts` file in `console-app` after updating the SDK version.

Actually after discussing this with @aosmakserato, I feel different about it. Maybe we don't need to create a major version. We can have a chat in our standup!

**Comment by aosmakserato** [comment]
> @mshahidi don't really need to, it's not used under `console-app` and on `profile-app` it's hardly use as it's optional so it's not a real break changes

Ended up deciding to release a major version to prevent having issues if someone runs npm update before we release changes

**Pull request merged**
